version: '3.8'

services:
  frontend:
    build:
      context: ./frontendapp
    ports:
      - "3000:80"
    environment:
      - VITE_APP_RAZORPAY_KEY=${VITE_APP_RAZORPAY_KEY}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backendapp
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI_ATLAS=${DB_URI_ATLAS}

      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    restart: unless-stopped